GITHUB_REPO=https://github.com/IRONKAGE/goit-devops-fp.git
# УВАГА: 172.18.0.2 - це зазвичай IP-адреса LocalStack у мережі Docker.
# Якщо Kaniko не зможе достукатися, перевірте IP через: docker inspect localstack_main_fp
ECR_REGISTRY=172.18.0.2:4566
REPO_NAME=django-app-fp-dev
